# Generated by Django 5.2.17 on 2026-09-24 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='open', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('changed_files', models.PositiveIntegerField(default=0)),
                ('files', models.JSONField(blank=True, default=list)),
                ('diff', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('unknown', 'Unknown'), ('clean', 'Clean'), ('reverted', 'Reverted'), ('bug_linked', 'Bug-linked'), ('hotfixed', 'Hotfixed')], default='unknown', max_length=20)),
                ('is_historical', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='anonymous', max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.pullrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.repository'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repo', 'number')},
        ),
    ]
