# Generated by Django 5.2.17 on 2026-09-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('rule', 'Rule-based'), ('ml', 'ML-based'), ('llm', 'LLM-based')], max_length=10)),
                ('risk', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('unavailable', 'Unavailable'), ('error', 'Error')], default='ok', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.pullrequest')),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['method'],
                'unique_together': {('pr', 'method')},
            },
        ),
    ]
