"""Generate a synthetic, labelled PR history so the whole app works with zero GitHub access.

The outcomes are drawn from a hidden formula plus noise, so no scorer can be perfect.
This is DEMO data only - never report numbers from it as research results.
"""
import math
import random
from datetime import timedelta

from django.core.management.base import BaseCommand
from django.utils import timezone

from core.models import PullRequest, Repository
from core.services import upsert_pull_request

VERBS = ["Fix", "Add", "Refactor", "Update", "Remove", "Improve", "Handle", "Migrate", "Optimize", "Clean up"]
NOUNS = ["retry logic", "session handling", "invoice totals", "user serializer", "cache keys", "login flow",
         "payment webhook", "search filters", "email templates", "rate limiter", "CSV export", "token refresh",
         "settings loader", "date parsing", "pagination", "audit log"]
AUTHORS = ["asha", "rohit", "meera", "dev-k", "nina", "sam", "priya", "leo"]
CODE = ["    return result", "    if user is None:", "        raise ValueError('missing user')", "    items = [i for i in items if i]",
        "    cache.set(key, value, timeout=300)", "    logger.info('done %s', name)", "    total += item.price * item.qty",
        "    for row in rows:", "        yield row", "    data = json.loads(payload)", "    session.commit()"]
PATHS = {
    "core": ["app/utils.py", "app/models.py", "app/views.py", "app/serializers.py", "app/services/orders.py", "web/helpers.js"],
    "sensitive": ["app/auth/login.py", "app/payments/charge.py", "app/security/tokens.py"],
    "config": ["Dockerfile", ".github/workflows/ci.yml", "requirements.txt", "app/settings.py"],
    "migration": ["app/migrations/0042_add_field.py"],
    "test": ["tests/test_utils.py", "tests/test_views.py", "tests/test_orders.py"],
    "docs": ["README.md", "docs/setup.md"],
}


def make_patch(rng, adds, dels):
    lines = [f"@@ -1,{dels + 3} +1,{adds + 3} @@"]
    lines += [f"+{rng.choice(CODE).strip()}" for _ in range(min(adds, 25))]
    lines += [f"-{rng.choice(CODE).strip()}" for _ in range(min(dels, 12))]
    if adds > 25 or dels > 12:
        lines.append("... (truncated in demo data)")
    return "\n".join(lines)


def build_pr(rng, i):
    kind = rng.choices(["docs", "small", "feature", "big", "infra"], weights=[12, 38, 30, 8, 12])[0]
    picks = []
    if kind == "docs":
        picks += rng.sample(PATHS["docs"], rng.randint(1, 2))
    else:
        n = {"small": (1, 3), "feature": (3, 8), "big": (12, 30), "infra": (1, 4)}[kind]
        for _ in range(rng.randint(*n)):
            picks.append(rng.choice(PATHS["core"]) if kind != "big" else f"app/module{rng.randint(1, 40)}/handlers.py")
        if rng.random() < 0.18 or (kind == "big" and rng.random() < 0.5):
            picks.append(rng.choice(PATHS["sensitive"]))
        if kind == "infra" or rng.random() < 0.10:
            picks.append(rng.choice(PATHS["config"]))
        if rng.random() < 0.08:
            picks.append(PATHS["migration"][0])
        if rng.random() < (0.35 if kind == "big" else 0.55):
            picks.append(rng.choice(PATHS["test"]))
    files, add_total, del_total = [], 0, 0
    for name in dict.fromkeys(picks):
        scale = {"small": 25, "feature": 60, "big": 70, "infra": 15, "docs": 12}[kind]
        adds = min(int(rng.lognormvariate(math.log(scale), 0.8)), 600)
        dels = int(adds * rng.uniform(0.1, 0.6))
        add_total += adds
        del_total += dels
        files.append({"filename": name, "status": "modified", "additions": adds, "deletions": dels,
                      "patch": make_patch(rng, adds, dels)})
    diff = "\n".join(f"--- a/{f['filename']}\n+++ b/{f['filename']}\n{f['patch']}" for f in files)

    names = [f["filename"] for f in files]
    churn = add_total + del_total
    z = (-3.7 + 0.36 * math.log1p(churn)
         + 0.9 * any(n in PATHS["sensitive"] for n in names)
         + 0.5 * any("migrations" in n for n in names)
         + 0.4 * any(n in PATHS["config"] for n in names)
         - 0.6 * any(n in PATHS["test"] for n in names)
         + rng.gauss(0, 0.9))
    p = 1 / (1 + math.exp(-z))
    if kind == "docs":
        p *= 0.1
    outcome = "clean"
    if rng.random() < p:
        outcome = rng.choices(["reverted", "bug_linked", "hotfixed"], weights=[4, 4, 2])[0]
    return {
        "title": f"{rng.choice(VERBS)} {rng.choice(NOUNS)}",
        "body": "Demo PR generated by seed_demo.",
        "author": rng.choice(AUTHORS), "state": "merged", "url": "",
        "additions": add_total, "deletions": del_total, "changed_files": len(files),
        "files": files, "diff": diff,
    }, outcome


class Command(BaseCommand):
    help = "Create a synthetic labelled PR history for demos and pipeline testing."

    def add_arguments(self, parser):
        parser.add_argument("--count", type=int, default=150)
        parser.add_argument("--seed", type=int, default=7)

    def handle(self, *args, count, seed, **opts):
        rng = random.Random(seed)
        repo, _ = Repository.objects.get_or_create(full_name="demo/payments-service", defaults={"is_demo": True})
        now = timezone.now()
        risky = 0
        for i in range(count):
            data, outcome = build_pr(rng, i)
            opened = now - timedelta(days=int(300 * (1 - i / count)) + rng.randint(0, 2), hours=rng.randint(0, 20))
            data.update(number=i + 1, opened_at=opened, merged_at=opened + timedelta(hours=rng.randint(2, 48)))
            upsert_pull_request(repo, data, outcome=outcome, is_historical=True)
            risky += outcome != "clean"
        self.stdout.write(self.style.SUCCESS(f"Seeded {count} demo PRs ({risky} risky) in {repo}."))
